trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and push the Docker image
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Restore packages'
            inputs:
              command: restore
              projects: '**/*.csproj'
          - task: DotNetCoreCLI@2
            displayName: 'Build project'
            inputs:
              command: build
              arguments: "--configuration Release"
          - task: DotNetCoreCLI@2
            displayName: 'Run tests'
            inputs:
              command: test
              projects: '**/*Tests/*.csproj'
              arguments: '--configuration Release'
          - task: Docker@1
            displayName: 'Build and push the Docker image'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'DockerHub'
              command: 'Build an image'
              dockerFile: '**/Dockerfile'
              imageName: '$(ImageName)'
              includeLatestTag: true
              useDefaultContext: false
              buildContext: './src/'
          - task: Docker@1
            displayName: 'Push the Docker image to Dockerhub'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'DockerHub'
              command: 'Push an image'
              imageName: '$(ImageName)'