trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.MD
      - '.github/*'

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.MD
      - '.github/*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  Runtime: 'linux-x64'

steps:
  - task: DotNetCoreCLI@2
    name: restore
    displayName: Restore packages
    inputs:
      command: 'restore'
      arguments: '-r $(Runtime)'
  - task: DotNetCoreCLI@2
    name: build
    displayName: Build project
    inputs:
      command: 'build'
      configuration: 'Release'
      projects: '**/Bot.csproj'
      arguments: '-r $(Runtime) -c Release --no-self-contained'
      publishWebProjects: false
  - task: DotNetCoreCLI@2
    name: test
    displayName: Run tests
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    name: publish
    displayName: Publish project
    inputs:
      command: 'publish'
      configuration: 'Release'
      projects: '**/Bot.csproj'
      arguments: '-r $(Runtime) -c Release -p:PublishReadyToRun=true -o $(Build.ArtifactStagingDirectory)'
      publishWebProjects: false
  - task: PublishBuildArtifacts@1
    name: pack
    displayName: Pack build
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'