//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created!.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///{0} {1} {2} {3}
        ///{4}
        ///Ratings:
        ///{5}
        ///        .
        /// </summary>
        internal static string ItemMessageTemplate {
            get {
                return ResourceManager.GetString("ItemMessageTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type a name of a new category.
        /// </summary>
        internal static string NewCategoryCommand {
            get {
                return ResourceManager.GetString("NewCategoryCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type a name of a new item.
        /// </summary>
        internal static string NewItemCommand {
            get {
                return ResourceManager.GetString("NewItemCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type a name of a new manufacturer.
        /// </summary>
        internal static string NewManufacturerCommand {
            get {
                return ResourceManager.GetString("NewManufacturerCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type a name of a new place.
        /// </summary>
        internal static string NewPlaceCommand {
            get {
                return ResourceManager.GetString("NewPlaceCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string RatingLineTemplate {
            get {
                return ResourceManager.GetString("RatingLineTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recorded.
        /// </summary>
        internal static string Recorded {
            get {
                return ResourceManager.GetString("Recorded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refreshed.
        /// </summary>
        internal static string Refreshed {
            get {
                return ResourceManager.GetString("Refreshed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select manufacturer.
        /// </summary>
        internal static string SelectManufacturer {
            get {
                return ResourceManager.GetString("SelectManufacturer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select place.
        /// </summary>
        internal static string SelectPlace {
            get {
                return ResourceManager.GetString("SelectPlace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to ratings bot. Type @rtngsbot in chat to see your ratings &amp; available items..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
